fix: fix Rust debug builds
The tests were failing with:

    thread 'test_repl' (67668) panicked at src/filters.rs:531:22:
    unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`

This commit replaces the unsafe code with safe code.